# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
export TERM=xterm-256color
export ZSH=$HOME/.zsh
# History won't save duplicates.
setopt HIST_IGNORE_ALL_DUPS

# History won't show duplicates on search.
setopt HIST_FIND_NO_DUPS
setopt autocd extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/mpoturai/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

PATH="$PATH:/home/mpoturai/.local/bin"
PATH="${HOME}/.bin:${PATH}"
PATH="/home/mpoturai/.local/share/go/bin:$PATH"
PATH="/home/mpoturai/fastdeploy/bin:$PATH"
export GIT_SSL_NO_VERIFY=1
xset r rate 250 50

function set-title() {
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1=${ORIG}${TITLE}
}
export PATH=~/.local/bin:"$PATH"
alias ghc="gh copilot suggest"
alias ls="exa"
alias cat="bat --theme ansi -Pp"
alias bbnice="nice -n 10 bitbake"


source $ZSH/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/zsh-256color/zsh-256color.plugin.zsh
source $ZSH/plugins/colors/colors.plugin.zsh
source $ZSH/plugins/colorize/colorize.plugin.zsh
source $ZSH/plugins/zsh-fzf-history-search/zsh-fzf-history-search.plugin.zsh
fpath=($ZSH/plugins/zsh-completions/src $fpath)
PROMPT="%F{red}%n%f %F{green}%~%f > "

export GZ_SIM_SYSTEM_PLUGIN_PATH=$HOME/gz_ws/src/ardupilot_gazebo/build:$GZ_SIM_SYSTEM_PLUGIN_PATH
export GZ_SIM_RESOURCE_PATH=$HOME/gz_ws/src/ardupilot_gazebo/models:$HOME/gz_ws/src/ardupilot_gazebo/worlds:$GZ_SIM_RESOURCE_PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

_fzf_compgen_path() {
  bfs -follow -exclude -name ".git" "$1" 2> /dev/null
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  bfs -type d -follow -exclude -name ".git" "$1" 2> /dev/null
}

alias fuck="git rebase --show-current-patch"

export XDG_CACHE_HOME=$HOME/.cache
alias paru="paru --bottomup"
