config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zsh:
    src: zsh
    dst: ~/.zsh
  f_alacritty.toml:
    src: config/alacritty.toml
    dst: ~/.config/alacritty.toml
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
profiles:
  mpoturai-pc:
    dotfiles:
    - f_zshrc
    - d_zsh
  ARCHBOX:
    include:
    - mpoturai-pc
    dotfiles:
    - f_alacritty.toml
    - f_picom.conf
