backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = true;
glx-swap-method = "3";


shadow = false;
no-dnd-shadow = true;
no-dock-shadow = true;
shadow-radius = 0;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-opacity = 0;




mark-ovredir-focused = true;
inactive-opacity = 0.9;

fading = false;
 # The time between steps in a fade in milliseconds. (default 10).
 fade-delta = 1;
 # Opacity change between steps while fading in. (default 0.028).
 fade-in-step = 0.03;
 # Opacity change between steps while fading out. (default 0.03).
 fade-out-step = 0.03;


opacity-rule = ["100:class_g = 'Termite'"];
#opacity-rule = ["100:name = 'i3lock'"]

