[window]
blur = true
opacity = 0.9
dynamic_padding = true
[keyboard]
bindings = [
{key = "k", mods = "Control|Shift",  action = "ScrollLineUp"},
{key = "j", mods = "Control|Shift",  action = "ScrollLineDown"},
{key = "ArrowUp", mods = "Control|Shift",  action = "ScrollHalfPageUp"},
{key = "ArrowDown", mods = "Control|Shift",  action = "ScrollHalfPageDown"},
]
